# Generated by Django 4.1.2 on 2022-10-16 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformationType',
            fields=[
                ('idInformationType', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('subSrting', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='column',
            name='information_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.informationtype'),
        ),
    ]
