# Generated by Django 4.1.2 on 2022-10-16 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_informationtype_alter_column_information_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='informationtype',
            old_name='subSrting',
            new_name='subString',
        ),
    ]
