# Generated by Django 4.1.2 on 2022-10-17 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_subsrting_informationtype_substring'),
    ]

    operations = [
        migrations.RenameField(
            model_name='column',
            old_name='information_type',
            new_name='informationType',
        ),
    ]
